// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLHS;

#nullable disable

namespace QLHS.Migrations
{
    [DbContext(typeof(EFDbContext))]
    partial class EFDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLHS.Models.Course", b =>
                {
                    b.Property<long>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Credits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DepartmentID")
                        .HasColumnType("bigint");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SemesterID")
                        .HasColumnType("bigint");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            CourseID = 101000001L,
                            CourseName = "Tổng quan về Hàng không dân dụng",
                            Credits = "3",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 1L,
                            SemesterName = "Học Kỳ 1"
                        },
                        new
                        {
                            CourseID = 101000009L,
                            CourseName = "Giáo dục thể chất-Sức nhanh *",
                            Credits = "1",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 1L,
                            SemesterName = "Học Kỳ 1"
                        },
                        new
                        {
                            CourseID = 101000373L,
                            CourseName = "Cơ sở dữ liệu",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 1L,
                            SemesterName = "Học Kỳ 1"
                        },
                        new
                        {
                            CourseID = 101000517L,
                            CourseName = "Toán cơ sở",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 1L,
                            SemesterName = "Học Kỳ 1"
                        },
                        new
                        {
                            CourseID = 101000525L,
                            CourseName = "Nhập môn ngành CNTT",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 1L,
                            SemesterName = "Học Kỳ 1"
                        },
                        new
                        {
                            CourseID = 101000746L,
                            CourseName = "Triết học Mác-Lênin",
                            Credits = "3",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 1L,
                            SemesterName = "Học Kỳ 1"
                        },
                        new
                        {
                            CourseID = 101000003L,
                            CourseName = "Pháp luật đại cương",
                            Credits = "2",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 2L,
                            SemesterName = "Học Kỳ 2"
                        },
                        new
                        {
                            CourseID = 101000083L,
                            CourseName = "Giáo dục thể chất-Võ Cổ Truyền *",
                            Credits = "1",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 2L,
                            SemesterName = "Học Kỳ 2"
                        },
                        new
                        {
                            CourseID = 101000087L,
                            CourseName = "Toán chuyên đề",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 2L,
                            SemesterName = "Học Kỳ 2"
                        },
                        new
                        {
                            CourseID = 101000510L,
                            CourseName = "Kiến trúc máy tính",
                            Credits = "2",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 2L,
                            SemesterName = "Học Kỳ 2"
                        },
                        new
                        {
                            CourseID = 101000747L,
                            CourseName = "Kinh tế chính trị Mác Lênin",
                            Credits = "2",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 2L,
                            SemesterName = "Học Kỳ 2"
                        },
                        new
                        {
                            CourseID = 101000966L,
                            CourseName = "Lập trình cơ bản",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 2L,
                            SemesterName = "Học Kỳ 2"
                        },
                        new
                        {
                            CourseID = 101001061L,
                            CourseName = "Tiếng Anh 1",
                            Credits = "3",
                            DepartmentID = 4L,
                            DepartmentName = "Khoa Ngoại Ngữ",
                            SemesterID = 2L,
                            SemesterName = "Học Kỳ 2"
                        },
                        new
                        {
                            CourseID = 101000015L,
                            CourseName = "Giáo dục quốc phòng- an ninh *",
                            Credits = "8",
                            DepartmentID = 0L,
                            DepartmentName = "",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            CourseID = 101000017L,
                            CourseName = "Cấu trúc dữ liệu và thuật giải",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            CourseID = 101000233L,
                            CourseName = "Giáo dục thể chất-Aerobic ",
                            Credits = "1",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            CourseID = 101000244L,
                            CourseName = "Chủ nghĩa xã hội khoa học",
                            Credits = "2",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            CourseID = 101000395L,
                            CourseName = "Hệ điều hành",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            CourseID = 101000846L,
                            CourseName = "Toán rời rạc",
                            Credits = "2",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            CourseID = 101000848L,
                            CourseName = "Lập trình hướng đối tượng",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            CourseID = 101001095L,
                            CourseName = "Tiếng Anh 2",
                            Credits = "3",
                            DepartmentID = 4L,
                            DepartmentName = "Khoa Ngoại Ngữ",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            CourseID = 101000016L,
                            CourseName = "Tư tưởng Hồ Chí Minh",
                            Credits = "2",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 3L,
                            SemesterName = "Học Kỳ 4"
                        },
                        new
                        {
                            CourseID = 101000849L,
                            CourseName = "Mạng máy tính",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 4L,
                            SemesterName = "Học Kỳ 4"
                        },
                        new
                        {
                            CourseID = 101000850L,
                            CourseName = "Phân tích và thiết kế thuật giải",
                            Credits = "2",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 4L,
                            SemesterName = "Học Kỳ 4"
                        },
                        new
                        {
                            CourseID = 101000854L,
                            CourseName = "Lập trình Web",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 4L,
                            SemesterName = "Học Kỳ 4"
                        },
                        new
                        {
                            CourseID = 101001119L,
                            CourseName = "Tiếng Anh 3",
                            Credits = "3",
                            DepartmentID = 4L,
                            DepartmentName = "Khoa Ngoại Ngữ",
                            SemesterID = 4L,
                            SemesterName = "Học Kỳ 4"
                        },
                        new
                        {
                            CourseID = 101001317L,
                            CourseName = "Lý thuyết đồ thị",
                            Credits = "2",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 4L,
                            SemesterName = "Học Kỳ 4"
                        },
                        new
                        {
                            CourseID = 101000020L,
                            CourseName = "Giáo dục thể chất-bóng rổ *",
                            Credits = "1",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 4L,
                            SemesterName = "Học Kỳ 4"
                        },
                        new
                        {
                            CourseID = 101000524L,
                            CourseName = "Lịch sử Đảng",
                            Credits = "2",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 5L,
                            SemesterName = "Học Kỳ 5"
                        },
                        new
                        {
                            CourseID = 101000851L,
                            CourseName = "Đồ án cơ sở ngành CNTT",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 5L,
                            SemesterName = "Học Kỳ 5"
                        },
                        new
                        {
                            CourseID = 101000856L,
                            CourseName = "Công nghệ phần mềm",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 5L,
                            SemesterName = "Học Kỳ 5"
                        },
                        new
                        {
                            CourseID = 101000859L,
                            CourseName = "Đồ họa máy tính",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 5L,
                            SemesterName = "Học Kỳ 5"
                        },
                        new
                        {
                            CourseID = 101000860L,
                            CourseName = "Quản trị mạng",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 5L,
                            SemesterName = "Học Kỳ 5"
                        },
                        new
                        {
                            CourseID = 101001120L,
                            CourseName = "Tiếng Anh 4",
                            Credits = "3",
                            DepartmentID = 4L,
                            DepartmentName = "Khoa Ngoại Ngữ",
                            SemesterID = 5L,
                            SemesterName = "Học Kỳ 5"
                        },
                        new
                        {
                            CourseID = 101000022L,
                            CourseName = "Giáo dục thể chất-bóng chuyền *",
                            Credits = "1",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 5L,
                            SemesterName = "Học Kỳ 5"
                        },
                        new
                        {
                            CourseID = 101000601L,
                            CourseName = "Pháp luật hàng không",
                            Credits = "2",
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ Bản",
                            SemesterID = 6L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000855L,
                            CourseName = "Lập trình thiết bị di động",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 6L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000858L,
                            CourseName = "Trí tuệ nhân tạo",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 6L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000861L,
                            CourseName = "Quản trị dự án CNTT",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 6L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000853L,
                            CourseName = "Lập trình Windows +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 6L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000863L,
                            CourseName = "Cơ sở dữ liệu nâng cao +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 6L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000865L,
                            CourseName = "Lập trình Game +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 6L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000866L,
                            CourseName = "Kiểm chứng phần mềm +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 6L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000875L,
                            CourseName = "An toàn và bảo mật thông tin +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            CourseID = 101000864L,
                            CourseName = "Đồ án chuyên ngành CNTT",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            CourseID = 101000869L,
                            CourseName = "Xử lý ảnh và thị giác máy tính",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            CourseID = 101000872L,
                            CourseName = "Lập trình Python",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            CourseID = 101000857L,
                            CourseName = "Hệ quản trị cơ sở dữ liệu +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            CourseID = 101000862L,
                            CourseName = "Phân tích thiết kế hệ thống +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            CourseID = 101000867L,
                            CourseName = "Máy học +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            CourseID = 101000868L,
                            CourseName = "Lập trình mạng +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            CourseID = 101000967L,
                            CourseName = "Xây dựng ứng dụng thương mại điện tử +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 7L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            CourseID = 101000878L,
                            CourseName = "Thực tập tốt nghiệp CNTT",
                            Credits = "4",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 8L,
                            SemesterName = "Học Kỳ 8"
                        },
                        new
                        {
                            CourseID = 101000870L,
                            CourseName = "Internet vạn vật (IoT) +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 8L,
                            SemesterName = "Học Kỳ 8"
                        },
                        new
                        {
                            CourseID = 101000871L,
                            CourseName = "Điện toán đám mây +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 8L,
                            SemesterName = "Học Kỳ 8"
                        },
                        new
                        {
                            CourseID = 101000873L,
                            CourseName = "Khai thác dữ liệu +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 8L,
                            SemesterName = "Học Kỳ 8"
                        },
                        new
                        {
                            CourseID = 101000874L,
                            CourseName = "Dữ liệu lớn +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 8L,
                            SemesterName = "Học Kỳ 8"
                        },
                        new
                        {
                            CourseID = 101000876L,
                            CourseName = "Công nghệ chuỗi khối +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 8L,
                            SemesterName = "Học Kỳ 8"
                        },
                        new
                        {
                            CourseID = 101000877L,
                            CourseName = "Mạng nơron và ứng dụng +",
                            Credits = "3",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 8L,
                            SemesterName = "Học Kỳ 8"
                        },
                        new
                        {
                            CourseID = 101000879L,
                            CourseName = "Khóa luận tốt nghiệp CNTT +",
                            Credits = "6",
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin",
                            SemesterID = 8L,
                            SemesterName = "Học Kỳ 6"
                        });
                });

            modelBuilder.Entity("QLHS.Models.Department", b =>
                {
                    b.Property<long>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1L,
                            DepartmentName = "Tất cả"
                        },
                        new
                        {
                            DepartmentID = 2L,
                            DepartmentName = "Khoa Công Nghệ Thông Tin"
                        },
                        new
                        {
                            DepartmentID = 3L,
                            DepartmentName = "Khoa Cơ bản"
                        },
                        new
                        {
                            DepartmentID = 4L,
                            DepartmentName = "Khoa Ngoại Ngữ"
                        });
                });

            modelBuilder.Entity("QLHS.Models.Grades", b =>
                {
                    b.Property<long>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GradeID"));

                    b.Property<long>("CourseID")
                        .HasColumnType("bigint");

                    b.Property<long>("FinalScores")
                        .HasColumnType("bigint");

                    b.Property<long>("MidScores")
                        .HasMaxLength(100)
                        .HasColumnType("bigint");

                    b.Property<string>("StudentCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentID")
                        .HasColumnType("bigint");

                    b.HasKey("GradeID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("QLHS.Models.Login", b =>
                {
                    b.Property<long>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentID"));

                    b.Property<string>("StudentPW")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentID");

                    b.ToTable("Login");

                    b.HasData(
                        new
                        {
                            StudentID = 2254810177L,
                            StudentPW = "21112004"
                        },
                        new
                        {
                            StudentID = 2254810159L,
                            StudentPW = "01072004"
                        },
                        new
                        {
                            StudentID = 2254810196L,
                            StudentPW = "28022004"
                        },
                        new
                        {
                            StudentID = 2254810246L,
                            StudentPW = "16012004"
                        },
                        new
                        {
                            StudentID = 2254810192L,
                            StudentPW = "10022004"
                        });
                });

            modelBuilder.Entity("QLHS.Models.LoginTC", b =>
                {
                    b.Property<long>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherID"));

                    b.Property<string>("TeacherPW")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherID");

                    b.ToTable("LoginTC");

                    b.HasData(
                        new
                        {
                            TeacherID = 1000002024L,
                            TeacherPW = "HVHK@2023"
                        },
                        new
                        {
                            TeacherID = 2000002024L,
                            TeacherPW = "HVHK@2024"
                        },
                        new
                        {
                            TeacherID = 3000002024L,
                            TeacherPW = "HVHK@2025"
                        });
                });

            modelBuilder.Entity("QLHS.Models.Semester", b =>
                {
                    b.Property<long>("SemesterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SemesterID"));

                    b.Property<long>("CourseID")
                        .HasColumnType("bigint");

                    b.Property<long>("DepartmentID")
                        .HasColumnType("bigint");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SemesterID");

                    b.ToTable("Semester");

                    b.HasData(
                        new
                        {
                            SemesterID = 1L,
                            CourseID = 0L,
                            DepartmentID = 0L,
                            SemesterName = "Học Kỳ 1"
                        },
                        new
                        {
                            SemesterID = 2L,
                            CourseID = 0L,
                            DepartmentID = 0L,
                            SemesterName = "Học Kỳ 2"
                        },
                        new
                        {
                            SemesterID = 3L,
                            CourseID = 0L,
                            DepartmentID = 0L,
                            SemesterName = "Học Kỳ 3"
                        },
                        new
                        {
                            SemesterID = 4L,
                            CourseID = 0L,
                            DepartmentID = 0L,
                            SemesterName = "Học Kỳ 4"
                        },
                        new
                        {
                            SemesterID = 5L,
                            CourseID = 0L,
                            DepartmentID = 0L,
                            SemesterName = "Học Kỳ 5"
                        },
                        new
                        {
                            SemesterID = 6L,
                            CourseID = 0L,
                            DepartmentID = 0L,
                            SemesterName = "Học Kỳ 6"
                        },
                        new
                        {
                            SemesterID = 7L,
                            CourseID = 0L,
                            DepartmentID = 0L,
                            SemesterName = "Học Kỳ 7"
                        },
                        new
                        {
                            SemesterID = 8L,
                            CourseID = 0L,
                            DepartmentID = 0L,
                            SemesterName = "Học Kỳ 8"
                        });
                });

            modelBuilder.Entity("QLHS.Models.Student", b =>
                {
                    b.Property<long>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DayOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentID = 2254810177L,
                            Address = "TP.Hồ Chí Minh",
                            Class = "22ĐHTT04",
                            DayOfBirth = new DateTime(2004, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "2254810177@vaa.edu.vn",
                            Gender = "Nam",
                            PhoneNumber = "0123456789",
                            StudentName = "Lê Tấn Đạt"
                        },
                        new
                        {
                            StudentID = 2254810159L,
                            Address = "TP.Hồ Chí Minh",
                            Class = "22ĐHTT04",
                            DayOfBirth = new DateTime(2004, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "2254810159@vaa.edu.vn",
                            Gender = "Nam",
                            PhoneNumber = "0123456968",
                            StudentName = "Đặng Nhật Hào"
                        },
                        new
                        {
                            StudentID = 2254810196L,
                            Address = "TP.Hồ Chí Minh",
                            Class = "22ĐHTT04",
                            DayOfBirth = new DateTime(2004, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "2254810196@vaa.edu.vn",
                            Gender = "Nam",
                            PhoneNumber = "0123456968",
                            StudentName = "Nguyễn Quốc Trí"
                        },
                        new
                        {
                            StudentID = 2254810246L,
                            Address = "TP.Hồ Chí Minh",
                            Class = "22ĐHTT04",
                            DayOfBirth = new DateTime(2004, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "2254810159@vaa.edu.vn",
                            Gender = "Nam",
                            PhoneNumber = "0123456968",
                            StudentName = "Trần Đình Anh Duy"
                        },
                        new
                        {
                            StudentID = 2254810192L,
                            Address = "Đồng Nai",
                            Class = "22ĐHTT04",
                            DayOfBirth = new DateTime(2004, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "2254810192@vaa.edu.vn",
                            Gender = "Nam",
                            PhoneNumber = "0123456789",
                            StudentName = "Trần Huy Hoàng"
                        });
                });

            modelBuilder.Entity("QLHS.Models.Teacher", b =>
                {
                    b.Property<long>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherID"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
